# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='시계열 그룹 아이디')),
                ('name', models.CharField(max_length=200, verbose_name='시계열 그룹 이름')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='시계열 그룹 생성 시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='시계열 그룹 수정 시간')),
            ],
            options={
                'verbose_name': '시계열',
                'verbose_name_plural': '시계열',
                'db_table': 'timeseries',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='시계열 관계 아이디')),
                ('email', models.CharField(db_column='email', default='', max_length=200, verbose_name='이메일')),
                ('projectInfo', models.ForeignKey(db_column='projectInfo', on_delete=django.db.models.deletion.CASCADE, related_name='projectInfo', to='projects.projects', verbose_name='프로젝트 아이디')),
                ('timeseriesId', models.ForeignKey(db_column='timeseriesId', on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='timeseries.timeseries', verbose_name='타임시리즈 아이디')),
            ],
            options={
                'verbose_name': '시계열 매핑',
                'verbose_name_plural': '시계열 매핑',
                'db_table': 'timeseries_relation',
            },
        ),
    ]
