# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layers2D',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='레이어 아이디')),
                ('properties', models.JSONField(default=list, verbose_name='레이어 속성 값')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='레이어 생성 시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='레이어 수정 시간')),
                ('issueCnt', models.IntegerField(default=0, verbose_name='이슈 개수')),
            ],
            options={
                'verbose_name': '2d 레이어 정보',
                'verbose_name_plural': '2d 레이어 정보들',
                'db_table': 'layers2d',
                'ordering': ['imgId'],
            },
        ),
        migrations.CreateModel(
            name='Layers2D3D',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='2d3d 레이어 아이디')),
                ('properties', models.JSONField(verbose_name='레이어 속성 값')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='레이어 생성 시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='레이어 수정 시간')),
            ],
            options={
                'verbose_name': '2d3d 레이어 정보',
                'verbose_name_plural': '2d3d 레이어 정보들',
                'db_table': 'layers2d3d',
            },
        ),
    ]
