# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0001_initial'),
        ('projects', '0001_initial'),
        ('processing', '0001_initial'),
        ('imgs', '0002_auto_20210624_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='layers2d3d',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='layers2d3d',
            name='mosaicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.mosaics', verbose_name='모자익 아이디'),
        ),
        migrations.AddField(
            model_name='layers2d3d',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='layers2d',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='layers2d',
            name='imgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs.imgs', verbose_name='이미지 아이디'),
        ),
        migrations.AddField(
            model_name='layers2d',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
    ]
