# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='유저 인덱스')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('plan', models.CharField(default='FREE', max_length=200, verbose_name='플랜')),
                ('phoneNumber', models.CharField(db_column='phone_number', max_length=20, verbose_name='연락처')),
                ('organization', models.CharField(max_length=200, verbose_name='조직 이름')),
                ('planEnrollmentDate', models.DateTimeField(auto_now_add=True, db_column='plan_enrollment_date', verbose_name='플랜 등록 일자')),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.users', to_field='email', verbose_name='이메일')),
                ('gigaPixel', models.BigIntegerField(db_column='giga_pixel', default=0, verbose_name='기가 픽셀')),
                ('pic', models.BigIntegerField(default=0, verbose_name='사진 용량')),
                ('vid', models.BigIntegerField(default=0, verbose_name='비디오 용량')),
                ('doc', models.BigIntegerField(default=0, verbose_name='도큐먼트 용량')),
                ('others', models.BigIntegerField(default=0, verbose_name='기타 용량')),
            ],
            options={
                'verbose_name': '용량',
                'verbose_name_plural': '용량',
                'db_table': 'storages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='계좌 정보 인덱스')),
                ('account', models.CharField(max_length=355, verbose_name='계좌 번호')),
                ('bank', models.CharField(max_length=50, verbose_name='은행')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일')),
            ],
            options={
                'verbose_name': '계좌 정보',
                'verbose_name_plural': '계좌 정보',
                'db_table': 'payment',
                'unique_together': {('email', 'account', 'bank')},
            },
        ),
    ]
