# Generated by Django 3.1.10 on 2021-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sectors',
            field=models.CharField(choices=[('건축', '건축'), ('토목', '토목'), ('안전진단', '안전진단'), ('서비스업', '서비스업'), ('기타', '기타')], db_column='sectors', default='기타', max_length=200, verbose_name='업종'),
        ),
    ]
