# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='dataprocessfile',
            name='dataprocessId',
            field=models.ForeignKey(blank=True, db_column='dataprocessId', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.dataprocess', verbose_name='데이터 프로세스 아이디'),
        ),
        migrations.AddField(
            model_name='dataprocessfile',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='dataprocess',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='dataprocess',
            name='projectId',
            field=models.OneToOneField(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='dataprocess', to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='anomalytypes',
            name='email',
            field=models.ForeignKey(db_column='email', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='anomalytypes',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_types', to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='anomalydegree',
            name='email',
            field=models.ForeignKey(db_column='email', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='anomalydegree',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_degree', to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('id', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='dataprocessfile',
            unique_together={('id', 'name', 'format')},
        ),
        migrations.AlterUniqueTogether(
            name='dataprocess',
            unique_together={('projectId', 'id', 'email')},
        ),
    ]
