# Generated by Django 3.1.10 on 2021-07-07 13:36

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210624_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalytypes',
            name='types',
            field=models.JSONField(default=projects.models.anomalyType_default_value, verbose_name='이슈 타입'),
        ),
        migrations.AlterField(
            model_name='dataprocess',
            name='coordinateSystem',
            field=models.CharField(blank=True, choices=[('EPSG:4326', 'EPSG:4326'), ('EPSG:3857', 'EPSG:3857'), ('EPSG:32652', 'EPSG:32652'), ('EPSG:32651', 'EPSG:32651'), ('EPSG:5186', 'EPSG:5186'), ('EPSG:5187', 'EPSG:5187')], db_column='coordinate_system', default='EPSG:4326', max_length=200, null=True, verbose_name='좌표 체계'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='coordinateSystem',
            field=models.CharField(db_column='coordinate_system', default='EPSG:3857', max_length=200, verbose_name='좌표 체계'),
        ),
    ]
