# Generated by Django 3.1.10 on 2021-08-17 15:38

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210806_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalytypes',
            name='types',
            field=models.JSONField(default=projects.models.anomalyType_default_value, verbose_name='이슈 타입'),
        ),
        migrations.AlterField(
            model_name='dataprocess',
            name='pointDensity',
            field=models.FloatField(default=0, verbose_name='점밀도'),
        ),
    ]
