# Generated by Django 3.1.10 on 2021-07-20 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20210720_0850'),
        ('processing', '0002_auto_20210624_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaics',
            name='dsmBound',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='dsm 영상 boundary'),
        ),
        migrations.AddField(
            model_name='mosaics',
            name='dsmConvertedDir',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='dsm 변환 파일 경로'),
        ),
        migrations.AddField(
            model_name='objects3d',
            name='offsetXYZ',
            field=models.JSONField(default=list, verbose_name='model offset'),
        ),
        migrations.AddField(
            model_name='objects3d',
            name='pcdConvertedFile',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Point Cloud Converted 파일 경로'),
        ),
        migrations.AlterField(
            model_name='mosaics',
            name='dsmDir',
            field=models.CharField(max_length=500, verbose_name='dsm 파일 경로'),
        ),
        migrations.AlterField(
            model_name='mosaics',
            name='volume',
            field=models.BigIntegerField(default=0, verbose_name='용량'),
        ),
        migrations.AlterUniqueTogether(
            name='mosaics',
            unique_together={('id', 'projectId', 'email')},
        ),
        migrations.RemoveField(
            model_name='mosaics',
            name='layerName',
        ),
        migrations.RemoveField(
            model_name='mosaics',
            name='wmsURL',
        ),
    ]
