# Generated by Django 3.1.10 on 2021-07-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_auto_20210720_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtls',
            name='d3ObjId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtl', to='processing.objects3d', verbose_name='3D 오브젝트 아이디'),
        ),
        migrations.AlterField(
            model_name='textures',
            name='d3ObjId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texture', to='processing.objects3d', verbose_name='3D 오브젝트 아이디'),
        ),
    ]
