# Generated by Django 3.1.10 on 2021-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_objects3d_contourfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects3d',
            name='coordSystem',
            field=models.CharField(default='4326', max_length=200, verbose_name='좌표계'),
        ),
    ]
