# Generated by Django 3.1.10 on 2021-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_objects3d_coordsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects3d',
            name='calibrated_external_camera_parameters',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='calibrated external camera parameters 경로'),
        ),
    ]
