# Generated by Django 3.1.10 on 2021-08-06 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210806_1402'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0007_objects3d_calibrated_external_camera_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastMosaics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='간편 모자익 아이디')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='간편 모자익 생성 일자')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='간편 모자익 수정 일자')),
                ('volume', models.BigIntegerField(default=0, verbose_name='용량')),
                ('mosaicDir', models.CharField(max_length=500, verbose_name='간편 이미지 모자익 파일 경로')),
                ('coordSystem', models.CharField(max_length=50, verbose_name='좌표계 정보')),
                ('mosaicSize', models.BigIntegerField(default=0, verbose_name='모자익 파일 사이즈')),
                ('bounds', models.JSONField(default=list, verbose_name='모자익 영상 boundary')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일')),
                ('projectId', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디')),
            ],
            options={
                'verbose_name': '간편 모자익',
                'verbose_name_plural': '간편 모자익',
                'db_table': 'fast_mosaic',
                'ordering': ['-id'],
                'unique_together': {('id', 'projectId', 'email')},
            },
        ),
    ]
