# Generated by Django 3.1.10 on 2021-06-24 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import utils.SetUploadPath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이미지 아이디')),
                ('name', models.CharField(max_length=200, verbose_name='이미지 이름')),
                ('format', models.CharField(max_length=10, verbose_name='포맷')),
                ('created', models.DateTimeField(verbose_name='이미지 생성 일자')),
                ('modified', models.DateTimeField(verbose_name='이미지 변경 일자')),
                ('size', models.IntegerField(verbose_name='파일 크기')),
                ('fileDir', models.ImageField(blank=True, null=True, upload_to=utils.SetUploadPath.compressionImg_upload_path, verbose_name='피일 경로')),
                ('annotationCnt', models.IntegerField(default=0, verbose_name='도식 수')),
                ('width', models.IntegerField(verbose_name='이미지 가로 픽셀')),
                ('height', models.IntegerField(verbose_name='이미지 세로 픽셀')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.SetUploadPath.thunmbnailImg_upload_path, verbose_name='썸네일 경로')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='사진 GPS 위치')),
                ('focalLength', models.FloatField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True, verbose_name='카메라 제작사')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='카메라 모델')),
                ('fNumber', models.FloatField(blank=True, null=True, verbose_name='F Number')),
                ('focalLengthIn35mmFilm', models.FloatField(blank=True, null=True, verbose_name='35mm 기준 focal length')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='이미지 고도')),
                ('isOptimized', models.BooleanField(default=True, verbose_name='이미지 중첩 최적화 여부')),
                ('isDibs', models.BooleanField(default=False, verbose_name='이미지 찜 여부')),
                ('filterDir', models.CharField(blank=True, max_length=200, null=True, verbose_name='필터 적용 결과 경로')),
                ('illuminationDelta', models.FloatField(default=0, verbose_name='이미지 명암 계수')),
                ('autoDelta', models.FloatField(default=0, verbose_name='이미지 자동 명암 계수')),
                ('iSOSpeedRatings', models.IntegerField(blank=True, null=True, verbose_name='ISO 감도')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지',
                'db_table': 'imgs',
                'ordering': ['created'],
            },
        ),
    ]
