# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.db import migrations, models
import utils.SetUploadPath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etc2D3DLayers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='2d3d 레이어 파일 아이디')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='2d3d 레이어 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=300, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.etcDoc_upload_path, verbose_name='파일 경로')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': '기타 2D&3D 레이어',
                'verbose_name_plural': '기타 2D&3D 레이어',
                'db_table': 'etc_2d3d_layers',
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='EtcDocs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='기타 문서 파일 아이디')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='기타 문서 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=300, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.etcDoc_upload_path, verbose_name='파일 경로')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': '기타 문서 파일',
                'verbose_name_plural': '기타 문서 파일',
                'db_table': 'etc_docs',
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='EtcImgs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='기타 이미지 파일 아이디')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='기타 이미지 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=300, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.etcImg_upload_path, verbose_name='파일 경로')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='이미지 가로')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='이미지 세로')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': '기타 이미지 파일',
                'verbose_name_plural': '기타 이미지 파일',
                'db_table': 'etc_imgs',
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='GCP 데이터')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='GCP 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=300, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.gcp_upload_path, verbose_name='파일 경로')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': 'GCP 데이터',
                'verbose_name_plural': 'GCP 데이터',
                'db_table': 'gcp',
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='NestedLayers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='중첩 파일 아이디')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='중첩 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=300, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.nestedLayer_upload_path, verbose_name='파일 경로')),
                ('coordSystem', models.CharField(blank=True, max_length=50, null=True, verbose_name='좌표계 정보')),
                ('convertedDir', models.CharField(blank=True, max_length=1000, null=True, verbose_name='변환 파일 경로')),
                ('isNexting', models.BooleanField(default=False, verbose_name='중첩 가능 여부')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': '레이어 중첩 파일',
                'verbose_name_plural': '레이어 중첩 파일',
                'db_table': 'nested_layers',
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='비디오 아이디')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='비디오 파일 이름')),
                ('ext', models.CharField(blank=True, max_length=200, null=True, verbose_name='확장자')),
                ('fileDir', models.FileField(upload_to=utils.SetUploadPath.video_upload_path, verbose_name='파일 경로')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('size', models.BigIntegerField(default=0, verbose_name='용량')),
            ],
            options={
                'verbose_name': '비디오 파일',
                'verbose_name_plural': '비디오 파일들',
                'db_table': 'video',
                'ordering': ['-uploadDate'],
            },
        ),
    ]
