# Generated by Django 3.1.10 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('etcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='video',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='nestedlayers',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='nestedlayers',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='gcp',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='gcp',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='etcimgs',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='etcimgs',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='etcdocs',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='etcdocs',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
        migrations.AddField(
            model_name='etc2d3dlayers',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='etc2d3dlayers',
            name='projectId',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='프로젝트 아이디'),
        ),
    ]
