# Generated by Django 3.1.10 on 2021-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etcs', '0004_nestedlayers_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedlayers',
            name='isEnroll',
            field=models.BooleanField(default=False, verbose_name='중첩 레이어 등록'),
        ),
    ]
